apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    run: backend-service
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: backend-service